### PR TITLE
Declare a minimum Node.js version

### PR DESCRIPTION
**Pull request by saubyk**
`package.json` carried no `engines` field, so npm installed RTL on any Node.js version without a word, and an unsupported runtime only surfaced later as a confusing failure at `node rtl` — as in #1220, where two users on Node 19.x/20.0.0 got `Cannot find module 'request-promise'` from an install that had reported success, and both were fixed by dropping to Node 18.15. (The dependency behind that particular report is gone: #1638 replaced `request`/`request-promise` with axios in 0.15.9.)

This sets `engines.node` to `>=20.19.0`, the floor the Angular 20 toolchain requires, so npm prints an `EBADENGINE` warning at install time instead. The docs disagreed with each other as well — `CONTRIBUTING.md` said "v14 & above" and the README gave no version at all; both now state the same floor.

### Judgment call

I used the plain `>=20.19.0` floor rather than Angular's exact `^20.19.0 || ^22.12.0 || >=24.0.0`, so odd-numbered Node lines (21, 23) don't emit a warning on every install. It still rejects the versions that broke #1220. This is advisory only — no `.npmrc` with `engine-strict`, so npm warns and continues rather than blocking anyone on a working-but-unusual Node.

### Verification

- `npm run lint` — clean
- backend tests — 40/40 pass
- frontend specs — 205/205 pass

No `frontend/` or `backend/` change: nothing under `server/` or `src/` was touched and the app version is unchanged, so neither artifact moves.

### CODE REVIEW

**Review by ShahanaFarooqui — APPROVED** [review]
LGTM!!!
